#ifndef KERNEL_H
#define KERNEL_H

#include "core.h"
#include "x86.h"
#include "synch.h"
#include "heap.h"
#include "task.h"
#include "process.h"
#include "vfs.h"
#include "syscall.h"
#include "elf.h"
#include "event_queue.h"
#include "ipc.h"
#include "idt.h"
#include "paging.h"

#include "ata.h"
#include "pci.h"
#include "rtl8139.h"
#include "rtc.h"
#include "sb16.h"
#include "uhci.h"
#include "kpu.h"
#include "net.h"

#include "tcp.h"
#include "dns.h"
#include "dhcp.h"
#include "fs.h"
#include "vga.h"
#include "kb.h"
#include "mouse.h"
#include "timer.h"

#include "window.h"
#include "desktop.h"
#include "shell.h"
#include "sysmon.h"
#include "fman.h"
#include "lang.h"
#include "boot.h"

#include "nn.h"
#include "model.h"
#include "aidemo.h"
#include "ai.h"
#include "ailab.h"
#include "aicreator.h"
#include "aistudio.h"

#include "edit.h"
#include "forth.h"
#include "paint.h"
#include "nnview.h"

#endif
